[package]
name = "rust-life-cycle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name="compare_str"
path="src/examples/compare_str.rs"