[package]
name = "rust-collections"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name="slice"
path="examples/slice.rs"

[[bin]]
name="slicederef"
path="examples/slice_deref.rs"